server.servlet.context-path: /wallet
spring.application.name: brokenwallet

spring.datasource:
  driver-class-name: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:mem:service
  username: sa
  password:
  hikari:
    connection-timeout: 10000
    idle-timeout: 600000
    max-lifetime: 1800000

spring.jpa:
  database: HSQL
  database-platform: org.hibernate.dialect.HSQLDialect
  show-sql: true
  properties:
    format_sql: true
    use_sql_comments: true
    use_minimum_puts: false
    use_second_level_cache: false
    use_query_cache: false
    cache_region_factory: org.hibernate.cache.internal.NoCachingRegionFactory
